name: Build and Create Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-linux-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          checkinstall \
          git \
          autoconf \
          automake \
          libtool-bin \
          libplist-dev \
          libusbmuxd-dev \
          libimobiledevice-glue-dev \
          libssl-dev \
          libusb-1.0-0-dev
        pip install cython

    - name: Prepare environment
      run: |
        echo "target_triplet=$(gcc -dumpmachine)" >> $GITHUB_ENV

    - name: Autogen
      run: ./autogen.sh PKG_CONFIG_PATH=/usr/local/lib/pkgconfig LDFLAGS="-Wl,-rpath=/usr/local/lib" --enable-debug

    - name: Make
      run: make

    - name: Prepare artifact
      run: |
        mkdir -p dest
        DESTDIR=$(pwd)/dest make install
        tar -C dest -czf libimobiledevice.tar.gz usr

    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: libimobiledevice-latest_${{env.target_triplet}}
        path: libimobiledevice.tar.gz

    - name: Save target triplet
      run: echo "${{ env.target_triplet }}" > target_triplet.txt

    - name: Upload target triplet
      uses: actions/upload-artifact@v4
      with:
        name: target_triplet
        path: target_triplet.txt

  create-docker-image:
    needs: build-linux-ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download target triplet
      uses: actions/download-artifact@v4
      with:
        name: target_triplet

    - name: Set target triplet
      run: echo "target_triplet=$(cat target_triplet.txt)" >> $GITHUB_ENV

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: libimobiledevice-latest_${{env.target_triplet}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: Dockerfile.runtime
